---
- name: New users are created by loop
  hosts: all
  become: true
  vars:
    web_users:
      - member
      - admin
      - developer

  tasks:
    - name: create database users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ db_users }}"
      when: "'dbservers' in group_names"

    - name: create webserver users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ web_users }}"
      when: "'webservers' in group_names"

