---
- name: set message of the day stored in /etc/motd
  hosts: docker
  become: true

  tasks:
    - name: change /etc/motd 
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
