---
- name: New user is created
  hosts: webservers
  become: true
  vars:
    username: test

  tasks:
    - name: user gets created
      user:
        name: "{{ username }}"
        state: present
